# -*- coding: utf-8 -*-
"""Assignment.2py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GCcn_oJdvpUI5Wnm0TMV3uZn6oAgPFQY
"""

import matplotlib.pyplot as plt
D, E, A, R = (2, 3.46), (0, 0), (5,0), (5,1)  
 
def line_gen(C1, C2):   
  return ((C1[0], C2[0]), (C1[1], C2[1]))  
l1 = line_gen(D, E)
l2 = line_gen(E, A)
l3 = line_gen(A, R)
l4 = line_gen(R, D)
 
def drawLine(line):   
  plt.plot(line[0], line[1])   
def drawVertix(coordinate, name):  
  plt.plot(coordinate[0], coordinate[1], 'o')   
  plt.text(coordinate[0] * (1 + 0.1), coordinate[1] * (1 - 0.1) , name)  
# drawing Quadrilateral
drawLine(l1)
drawLine(l2)
drawLine(l3)
drawLine(l4)
 # plotting vertices
drawVertix(D, "D")
drawVertix(E, "E")
drawVertix(A, "A")
drawVertix(R,"R") 
plt.xlabel('x - axis')
plt.ylabel('y - axis')
plt.title('Quadrilateral DEAR')
plt.grid()
plt.show()