# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1biCZ14sILBuKkuyqLDmDamUvh-aC1sQ0
"""

#Code by K.A. Raja Babu
#May 26, 2021
import numpy as np
import matplotlib.pyplot as plt
from coeffs import * #referred from G.V.V sir's Code

#centre and radius of circles
O1=np.array([6,0])
O2=np.array([-2,0])
r=5

#points on circle
A1=np.array([O1[0]+r,O1[1]])
A2=np.array([O2[0]+r,O2[1]])

#Generating lines
x_OA1 = line_gen(O1,A1)
x_OA2 = line_gen(O2,A2)

#Plotting lines
plt.plot(x_OA1[0,:],x_OA1[1,:],label='$r=5$')
plt.plot(x_OA2[0,:],x_OA2[1,:],label='$r=5$')

#Plotting circle1
c1 = 5
theta1 = np.linspace(0,2*np.pi,50)
x1 = c1*np.cos(theta1)
y1 = c1*np.sin(theta1)

plt.plot(x1+6,y1,label='$circle1$')

#Plotting circle2
c2 = 5
theta2 = np.linspace(0,2*np.pi,50)
x2 = c2*np.cos(theta2)
y2 = c2*np.sin(theta2)

plt.plot(x2-2,y2,label='$circle2$',color='r')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.plot(2,3,'o')
plt.text(1.8,3.5,'A')
plt.plot(6,0,'o')
plt.text(5.8,0.3,'O')
plt.plot(-2,0,'o')
plt.text(-2.2,0.3,'O')
plt.legend(loc='upper right')
plt.grid() # minor
plt.axis('equal')
plt.show()