#Code by GVV Sharma
#July  8, 2020
#released under GNU GPL
#Accompanying file for plotting data generated by triangle.m

import numpy as np
import matplotlib.pyplot as plt
#from coeffs import *

#if using termux
import subprocess
import shlex
#end if


x = np.loadtxt('triangle.dat',dtype='double')

##Generating all lines
x_AB = np.vstack((x[0,:], x[1,:]))
x_BC = np.vstack((x[2,:], x[3,:]))
x_CA = np.vstack((x[4,:], x[5,:]))
x_CM = np.vstack((x[6,:], x[7,:]))
x_MD = np.vstack((x[8,:], x[9,:]))
x_DB = np.vstack((x[10,:], x[11,:]))

#Plotting all lines
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_BC[0,:],x_BC[1,:],label='$BC$')
plt.plot(x_CA[0,:],x_CA[1,:],label='$CA$')
plt.plot(x_CM[0,:],x_CM[1,:],label='$CM$')
plt.plot(x_MD[0,:],x_MD[1,:],label='$MD$' )
plt.plot(x_DB[0,:],x_DB[1,:],label='$DB$' )


plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')

#if using termux
plt.savefig('./figs/tri_sss.pdf')
plt.savefig('./figs/tri_sss.eps')
subprocess.run(shlex.split("termux-open ./figs/tri_sss.pdf"))
#else
#plt.show()








