# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pHvnCNsFSeUcnvYWFYrT2sA2YOYofD42
"""

import numpy as np
Q = np.array([[8/np.sqrt(73),-3/(73*np.sqrt(73))],[3/np.sqrt(73),8/(73*np.sqrt(73))]])
R = np.array([[np.sqrt(73),46/np.sqrt(73)],[0,1/(73*np.sqrt(73))]])
A = Q@R 
print(A)
