# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z6sYUBAUjFEQH5fkOdlw_umEvJT_Wu2O
"""

import numpy as np

a = 4
b = 5
c = 6

M = np.matrix([[-a**2, a*b, a*c], [b*a, -b**2, b*c], [c*a, c*b, -c**2]])

print('Matrix is ')
print(M)
print('\n')
determinant = np.linalg.det(M)
print(determinant)

print(4 * a**2 * b**2 * c**2)