# -*- coding: utf-8 -*-
"""Assignment-11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WkFavAL_bXvvWWXrzM55C41yEK2XbDJg
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Plotting line 3x+4y = 60
A=np.array([0,15])
B=np.array([20,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='4x+3y=60')

#Plotting line x+3y=30
P=np.array([0,10])
Q=np.array([15,5])
PQ=line_gen(P,Q)
plt.plot(PQ[0,:],PQ[1,:],label='x+3y=30')

#Shading Required Region
x1=[0,0,12,20]
y1=[0,10,6,0]
plt.fill(x1,y1,color='green',alpha=0.3)

#Labelling points
plt.plot(0,10,'o',color='r')
plt.text(0.2,10.5,'A(0,10)')
plt.plot(12,6,'o',color='r')
plt.text(12.2,6.2,'B(12,6)')
plt.plot(20,0,'o',color='r')
plt.text(20.2,0.2,'C(20,0)')

plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()