# -*- coding: utf-8 -*-
"""Assignment5(1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Rf4qO2-3-PrCp3Os2gwW8yKaD7Gn1Vi
"""

# -*- coding: utf-8 -*-
"""ChallengeProblem3_1ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1m1ZYhjORqWvnK13fx9UzaQS_hqH7AqSc
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2, 2, 100)

y = 3*x**2 - 5*x + 2 

a = 3
b = -5
c = 2

d1 = -b + np.sqrt(b**2-4*a*c)
d2 = -b - np.sqrt(b**2-4*a*c)
d1 = d1/(2*a)
d2 = d2/(2*a)

plt.plot(x,y,label='y=3$x^2$-5x+2')
plt.grid()

plt.plot(d2,0, 'o')
plt.text(d2,0.6, 'A')
plt.plot(d1, 0, 'o')
plt.text(d1,1.0, 'B')
plt.plot(5/6,-1/12, 'o')
plt.text(0.83,-0.083,'c')

#show plot
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend()

plt.show()