# -*- coding: utf-8 -*-
"""Assignment10_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KEV2r7HjqMPc0u4PKHOOQbIWP9sjE2zV
"""

#September Sales(in Rupees)
#Code by K.A. Raja Babu
#June 14 ,2021
import numpy as np
import matplotlib.pyplot as plt
  
N = 2
ind = np.arange(N) 
width = 0.25
  
xvals = [10000,50000]
bar1 = plt.bar(ind, xvals, width, color = 'r')
  
yvals = [20000,30000]
bar2 = plt.bar(ind+width, yvals, width, color='g')
  
zvals = [30000,10000]
bar3 = plt.bar(ind+width*2, zvals, width, color = 'b')
  
plt.xlabel("Farmers")
plt.ylabel('Sales(in Rupees)')
plt.title("September Sales(in Rupees)")
  
plt.xticks(ind+width,['Ramkishan', 'Gurucharan Singh'])
plt.legend( (bar1, bar2, bar3), ('Basmati', 'Permal', 'Naura') )
plt.show()