# -*- coding: utf-8 -*-
"""Assignment-10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sbYJCWKCYjCSiyeoasa_jnVY2IoIX8BP
"""

import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Plotting line x+y = 6
A=np.array([6,0])
B=np.array([0,6])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='x+y=6')
 
#Plotting line x+y=4
P=np.array([4,0])
Q=np.array([0,4])
PQ=line_gen(P,Q)
plt.plot(PQ[0,:],PQ[1,:],label='x+y=4')
 
#Shading Required Region
x1=[0,6,4,0]
y1=[6,0,0,4]
plt.fill(x1,y1,color='blue',alpha=0.3)
 
#Labelling points
plt.plot(6,0,'o',color='r')
plt.text(6,0,'A(6,0)')
plt.plot(0,4,'o',color='r')
plt.text(0,4,'B(0,4)')

 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()