# -*- coding: utf-8 -*-
"""Assignment10_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NdH0QVAvN5_juirzMCkm3-qQldiyCrx-
"""

#Profit for Sales in October(in Rupees)
#Code by K.A. Raja Babu
#June 14 ,2021
import numpy as np
import matplotlib.pyplot as plt
  
N = 2
ind = np.arange(N) 
width = 0.25
  
xvals = [100,400]
bar1 = plt.bar(ind, xvals, width, color = 'r')
  
yvals = [200,200]
bar2 = plt.bar(ind+width, yvals, width, color='g')
  
zvals = [120,200]
bar3 = plt.bar(ind+width*2, zvals, width, color = 'b')
  
plt.xlabel("Farmers")
plt.ylabel('Sales(in Rupees)')
plt.title("Profit for Sales in October(in Rupees)")
  
plt.xticks(ind+width,['Ramkishan', 'Gurucharan Singh'])
plt.legend( (bar1, bar2, bar3), ('Basmati', 'Permal', 'Naura') )
plt.show()