# -*- coding: utf-8 -*-
"""Cross Product Check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pXqBOADpiBmKehdAuNJVxzZwrNEzfVR5
"""

import numpy as np

x = [2, -4, -5]
y = [1, -2, -3]
p=np.cross(x, y)

print(p)