# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jJkIwIH-iEAThj1gQs42OREnZm1_OrS_
"""

import sympy as sp
a,b,c = sp.symbols(['a','b','c'])
#Given matrices
A = sp.Matrix([[a,a**2,b*c],[b,b**2,c*a],[c,c**2,a*b]])
B = sp.Matrix([[1,a**2,a**3],[1,b**2,b**3],[1,c**2,c**3]])
#Finding determinants
l = A.det()
m = B.det()
# For proving that determinants are equal
if l==m:
  print("Both the determinants are equal")
else:
  print("Both the determinants are not equal")
