# -*- coding: utf-8 -*-
"""ChallengeProblem3_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15lra-5I_6Euqd7kFh3JWn-IStASi4Daj
"""

#Code by K.A. Raja Babu 
#June 22,2021
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-20, 20, 100)

y = -1*x**2 + 4*x + 9

plt.plot(x,y,label='y=-$x^2$+4x+9')
plt.grid()

plt.plot(2,13, 'o')
plt.text(2.5,14,'$c$')
plt.plot(2+13**(0.5),0, 'o')
plt.plot(2-13**(0.5),0, 'o')
plt.text(5.9,0.5,'$B$')
plt.text(-3.4,0.5,'$A$')

#show plot
plt.ylim([-15,20])
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend()

plt.show()