# -*- coding: utf-8 -*-
"""ChallengeProblem3_1ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m1ZYhjORqWvnK13fx9UzaQS_hqH7AqSc
"""

#Code by K.A. Raja Babu 
#June 21,2021
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2, 2, 50)

y = 6*x**2 - x - 2 

a = 6
b =-1
c =-2

d1 = -b + np.sqrt(b**2-4*a*c)
d2 = -b - np.sqrt(b**2-4*a*c)
d1 = d1/(2*a)
d2 = d2/(2*a)

plt.plot(x,y,label='y=6$x^2$-x-2')
plt.grid()

plt.plot(d2,0, 'o')
plt.text(d2,0.6, 'A')
plt.plot(d1, 0, 'o')
plt.text(d1,0.7, 'B')
plt.plot(1/12,-49/24, 'o')
plt.text(0.07,-1.50,'c')

#show plot
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend()

plt.show()