# -*- coding: utf-8 -*-
"""Assignment-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O-K9WnJtMpLfc7Nbh_L4nIHEE0a3hFRW
"""

# -*- coding: utf-8 -*-

"""Assignment-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O-K9WnJtMpLfc7Nbh_L4nIHEE0a3hFRW#scrollTo=pXVvd2LjeYLY
"""


import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2,4,100)
p=np.poly1d([2,-4,3])
for i in range(len(x)):
    y=p(x)

plt.plot(x,y)
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()
