# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nbCzcMdYvZxVl-spi0VQCyIc6Y9HO__d
"""

#code by Satya Sangram
#Parabola for quadforms 2.30
import numpy as np
import matplotlib.pyplot as plt
from coeffs import *

y = np.linspace(-5,5,100)
x=(y*y)/8
plt.plot(x,y,label='$y^2=8x$')
plt.xlabel('$x$')
plt.ylabel('$y$')

#Plotting directrix
#equation of directrix is given x=-2
P=np.array([-2,-7])
Q=np.array([-2,7])
A=line_gen(P,Q)
plt.plot(A[0,:],A[1,:],label='$directrix$')

#plotting focus
plt.plot(2,0,'o',label='$focus$')
plt.text(2.2,0.2,'F')
plt.legend(loc='best')
plt.grid()
plt.xlim([-3,5])



plt.show()