# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/102U6yu3rp5LbcW8XSaeIK2jw0MzRs18R
"""

#Code by Satya_Sangram
#Figure for Quadforms Q.No 2.37
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA

#Given Points
p = np.array(([4,3]))
q = np.array(([-1,4]))
P = np.diag(p)
Q = np.diag(q)
c = np.array(([0,0]))

dA = np.block([[p@P],[q@Q]])
db = np.array(([1,1]))

#Ellipse parameters
d = LA.solve(dA,db)
a = np.sqrt(1/d[0])
b = np.sqrt(1/d[1])

len = 50
theta = np.linspace(0,2*np.pi,len)
x_ellipse = np.zeros((2,len))
x_ellipse[0,:] = a*np.cos(theta)
x_ellipse[1,:] = b*np.sin(theta)

#Major and Minor Axes
MajorStandard = np.array(([a,0]))
MinorStandard = np.array(([0,b]))


#Plotting the standard ellipse
plt.plot(x_ellipse[0,:],x_ellipse[1,:],label='Standard ellipse')


#Labeling the coordinates
plt.plot(c[0],c[1],'o')
plt.plot(p[0],p[1],'o')
plt.plot(q[0],q[1],'o')
plt.text(4.1,3.2,'p')
plt.text(-1.1,3.5,'q')
plt.text(0.1,-0.3,'c')


plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='lower right')
plt.grid() # minor
plt.axis('equal')
plt.show()
