# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mnBOp9oyfCqsyMtmUJFiUYN6H1cQO0u_
"""

#Code by Satya_Sangram
#Figure for Quadforms Q.No 2.37
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA

for x in np.linspace(-1,3,10):
  p = np.array(([4-x,3]))
  q = np.array(([-1-x,4]))
  P = np.diag(p)
  Q = np.diag(q)
  

  dA = np.block([[p@P],[q@Q]])
  db = np.array(([1,1]))
  #Ellipse parameters
  d = LA.solve(dA,db)
  if(d[0]>0 and d[1]>0):
    a = np.sqrt(1/d[0])
    b = np.sqrt(1/d[1])
  
  
  len = 50
  theta = np.linspace(0,2*np.pi,len)
  x_ellipse = np.zeros((2,len))
  x_ellipse[0,:] = x+a*np.cos(theta)
  x_ellipse[1,:] = b*np.sin(theta)

  #Plotting the ellipses
  if(a>b):
    plt.plot(x_ellipse[0,:],x_ellipse[1,:])

plt.plot(4,3,'o')
plt.plot(-1,4,'o')
plt.text(4.1,3.2,'p')
plt.text(-1.1,3.5,'q')
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.grid() # minor
plt.axis('equal')
plt.show()