# -*- coding: utf-8 -*-
"""Assignment14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aHaRl-HMGWRpozCm5YhEOHs3KudJ8y3
"""

#PMF of X
#Code by K.A. Raja Babu
#July 05 ,2021

from scipy.stats import binom
import matplotlib.pyplot as plt

#Defining input values
v=[0,1,2,3]
x=[-4.5,-1,2.5,6]

#Calculating pmf 
p_x=[0.4005+0.0153*x1-0.0102*x1*x1 for x1 in x]

#Print pmf values 
print("x \t p(x)")
for i in v :
  print(str(x[i]) + "\t" + str(p_x[i]))

#Plotting the pmf graph
data = {'-4.5':1/8, '-1':3/8, '2.5':3/8, '6':1/8}
key = list(data.keys())
value = list(data.values())
plt.stem(key,value,use_line_collection = True)
plt.xlabel("$x$")
plt.ylabel("$p_{X}(x)$")
plt.title("PMF of $X$")
plt.show()