# -*- coding: utf-8 -*-
"""Assignment7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kVsVsFJP4HSWKu2jEDouRPNeENr2CvOz
"""

#Code by K.A Raja Babu
#June 09, 2021

import numpy as np
import matplotlib.pyplot as plt
from coeffs import * #refered from G.V.V sir's code

O = np.array(([0,0]))

def ellipse_gen(a,b):
	len = 50
	theta = np.linspace(0,2*np.pi,len)
	x_ellipse = np.zeros((2,len))
	x_ellipse[0,:] = a*np.cos(theta)
	x_ellipse[1,:] = b*np.sin(theta)
	x_ellipse = (x_ellipse.T + O).T
	return x_ellipse

#Standard Ellipse
a = 2
b = 6
x = ellipse_gen(a,b)

#Vertices
A1 = np.array([a,0])
A2 = -A1
B1 = np.array([0,b])
B2 = -B1

#Plotting the ellipse
plt.plot(x[0,:],x[1,:],'b' ,label='ellipse')

#Labelling points
plt.plot(2,0, 'o')
plt.text(2.3 ,-0.2,'A')
plt.plot(0,6, 'o')
plt.text(0.1 ,6.1,'B')
plt.plot(0,0, 'o')
plt.text(-0.7 ,-0.3,'O')

#Plotting line AB
A=np.array([a,0])
B=np.array([0,b])
AB = line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],'g')

#Plotting line OA
O=np.array([0,0])
A=np.array([a,0])
OA = line_gen(O,A)
plt.plot(OA[0,:],OA[1,:],'g')

#Plotting line OB
O=np.array([0,0])
B=np.array([0,b])
OB = line_gen(O,B)
plt.plot(OB[0,:],OB[1,:],'g')


plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')

plt.show()