# -*- coding: utf-8 -*-
"""EE3900As4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z3yISaLwaI2f0lju3f-RkpuHgQKq7d9T
"""

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# a plane is a*x+b*y+c*z+d=0
# [a,b,c] is the normal.
normal = np.array([1, 2, -5])
d = 9

# create x,y
xx, yy = np.meshgrid(range(10), range(10))

# calculate corresponding z
zz = ((-normal[0] * xx) - (normal[1] * yy) - (d)) *( 1 /normal[2])

# plot the surface
plt3d = plt.figure().gca(projection='3d')
plt3d.set_xlim3d(0,10)
plt3d.set_ylim3d(0,10)
plt3d.set_zlim3d(0,10)
plt3d.plot_surface(xx, yy, zz)

# plot the line
lam = np.arange(-10,10,0.1)
n = len(lam)
x  = np.ones(n)+ lam*1
y = np.ones(n)*2+lam*2
z = np.ones(n)*(3)+lam*(-5)
plt3d.plot(x,y,z)
#plt3d.scatter(0,0,8)

plt3d.view_init(9.5,20)