# -*- coding: utf-8 -*-
"""ASSIGNMENT10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3evN88AB6dpPI7f0Ztl77A3d4ouU5Ds
"""

# -*- coding: utf-8 -*-
"""Assignment10.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1ZKbFC8mv277gmtVOwYBrpIxWEn1XjCxW
"""

#Code by B.ANUSHA
#July 01,2021

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

A = np.array([[3,4],[5,2]]).T
b = np.array([8,11]).reshape((2,-1 ))
c = np.array([60,80])

x = Variable((2,1),nonneg = True)

f = c@x
obj = Minimize(f)
# Constraints
constraints = [A.T@x >= b]
Problem(obj, constraints).solve()

print("Minimum_value: " ,(f.value))
print("attained at: ",(x.value))

#Generating and plotting line 3x+4y = 8
A=np.array([5,-1.8])
B=np.array([-1.8,3.4])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='3x+4y=8')

#Generating and plotting line 5x+2y = 11
C=np.array([-0.5,6.7])
D=np.array([3,-1.8])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='5x+2y=11')

#Shading Required Region
x1=[C[0],8/3,A[0],2]
y1=[C[1],11/2,A[1],1/2]
plt.fill(x1,y1,color="gray",alpha=0.7)

#Labelling points
plt.plot(2,1/2,'o',color='r')
plt.text(2,1,'A(2,1/2)')

plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')