# -*- coding: utf-8 -*-
"""ASSIGNMENT4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttz5ucjuVuoqsV9ZW3DMig3gA4-C8HLZ
"""

import numpy as np
import matplotlib.pyplot as plt
import math

#if using termux
import subprocess
import shlex
#end if

x = np.linspace(-5, 5, 1000)
x1 = np.linspace(-1, 3, 1000) 
x2 = np.linspace(0, 4, 1000)
y = x*x/4.0
y1 = 3 - x1
y2 = x2 - 1
p = np.array([1, 2])
q = np.array([2, 1])
plt.plot(x, y, '-', label='$x^2 = 4y$')
plt.plot(p[0], p[1], 'o')
plt.text(p[0] + 0.1, p[1] + 0.1, 'P')
plt.plot(q[0], q[1], 'o')
plt.text(q[0] + 0.2, q[1] + 0.1, 'Q')
plt.plot(x1, y1, '-', label='$x + y = 3$')
plt.plot(x2, y2, '-', label='$x - y = 1$')
plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()