# -*- coding: utf-8 -*-
"""Assignment10_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zrBcjRn68QB-_0dv4hBvW7LCaAd1dZt
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Generating and plotting line 2x+y = 60
A=np.array([0,60])
B=np.array([30,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='2x+y=60')

#Generating and plotting line x = 20
C=np.array([20,0])
D=np.array([20,60])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='x=20')

#Generating and plotting line 2x+3y=120
E=np.array([0,40])
F=np.array([60,0])
EF=line_gen(E,F)
plt.plot(EF[0,:],EF[1,:],label='2x+3y=120')



#Shading Required Region
x1=[20,20,15,0,0]
y1=[0,20,30,40,0]
plt.fill(x1,y1)

#Labelling points
plt.plot(20,0,'o',color='r')
plt.text(20.2,0.2,'A(20,0)')
plt.plot(20,20 ,'o',color='r')
plt.text(20.5,20.5,'B(20,20)')
plt.plot(15,30,'o',color='r')
plt.text(15.3,30.3,'C(15,30)')
plt.plot(0,40,'o',color='r')
plt.text(0.3,40.3,'D(0,40)')


plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')