# -*- coding: utf-8 -*-
"""Assignment10_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CKoRaFwwrtvqt17AcoAg4-jbs79OPMyJ
"""

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[2,1],[1,0],[2,3]]).T
b = np.array([60,20,120]).reshape((3,-1))
c = np.array([7.5,5])

x = Variable((2,1),nonneg = True)

f = c@x
obj = Maximize(f)
# Constraints
constraints = [A.T@x <= b]
Problem(obj, constraints).solve()

print("Maximum_value: " ,(f.value))
print("attained at: ",(x.value))