# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1oAtnJtVDE9HLBvjNElyxa--yhn4-eW
"""

import numpy as np
import matplotlib.pyplot as plt
import math

# vectors P and U
P = np.array([0,0])
U = np.array([6.5,0])
# find angles UPM and JPU (in radians)
cos1 = ((5**2)+(6.5**2)-(4**2))/(2*5*6.5)
cos2 = ((6.5**2+4.5**2-3.5**2))/((2*6.5*4.5))
th1 =  math.acos (cos1)
th2 =  math.acos (cos2)
print("angle1: ",math.degrees(th1))
print("angle2: ",math.degrees(th2))

# find coordinates of M and J
M = np.array([math.cos(th1),math.sin(th1)])*5
J = np.array([math.cos(th2),-math.sin(th2)])*4.5

#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

x_PU = line_gen(P,U)
x_UM = line_gen(U,M)
x_MP = line_gen(M,P)
x_PJ = line_gen(P,J)
x_JU = line_gen(J,U)

#plotting
plt.plot(x_UM[0,:],x_UM[1,:],label='$UM$')
plt.plot(x_MP[0,:],x_MP[1,:],label='$MP$')
plt.plot(x_PJ[0,:],x_PJ[1,:],label='$PJ$')
plt.plot(x_JU[0,:],x_JU[1,:],label='$JU$')
plt.plot(x_PU[0,:],x_PU[1,:],label='$PU$')

plt.plot(P[0], P[1], 'o')
plt.text(P[0]-(0.21), P[1]+(0.2),'P')
plt.plot(M[0],M[1], 'o')
plt.text(M[0]*(1 + 0.02),M[1]*(1),'M')
plt.plot(U[0],U[1],'o')
plt.text(U[0]*(1 + 0.04), U[1]*(1),'U')
plt.plot(J[0],J[1],'o')
plt.text(J[0]*(1+0.001),J[1]*(1-0.1),'J')

plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show