# -*- coding: utf-8 -*-
"""Assignment-9.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M9b3YB5yi-pRP0LQna3c_1CQf1xq_1oM
"""

import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Generating and plotting line x+2y = 28
A=np.array([0,14])
B=np.array([28,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='x+2y= 28')
 
#Generating and plotting line 3x+y = 24
C=np.array([2,18])
D=np.array([8,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='3x+y=24')
 
 
#Shading Required Region
x1=[0,8,4,0]
y1=[0,0,12,14]
plt.fill(x1,y1)
 
#Labelling points
plt.plot(8,0,'o',color='r')
plt.text(8,0,'A(8,0)')
plt.plot(4,12,'o',color='r')
plt.text(4,12,'B(4,12)')
plt.plot(0,14,'o',color='r')
plt.text(0,14,'C(0,14)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')