# -*- coding: utf-8 -*-
"""Assignment-9.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F34yru_47qWnXvnhD5mGIvdOoh9-HCHJ
"""

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt
 
A = np.array([[1,2],[3,1]]).T
b = np.array([28,24]).reshape((2,-1 ))
c = np.array([20,10])
 
x = Variable((2,1),nonneg = True)
 
f = c@x
obj = Minimize(f)
# Constraints
constraints = [A.T@x >= b]
Problem(obj, constraints).solve()
 
print("Maximum_value: " ,(f.value))
print("attained at: ",(x.value))