# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gBGwIl84Pkm3JlwxnkTmHQivltiMEo4a
"""

import numpy as np

A = np.array([[2,4],[3,2]])
B = np.array([[1,3],[-2,5]])

print(A-B)