# -*- coding: utf-8 -*-
"""Assignment12_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pgYjYVeGOCAPs25WqFnnkVuqs5GyECWx
"""

#Code by K.A. Raja Babu
#June 19, 2021

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Generating and plotting line x+5y = 115
A=np.array([0,23])
B=np.array([115,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='x+5y=115')

#Generating and plotting line 4x+y = 80
C=np.array([0,80])
D=np.array([20,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='4x+y=80')

#Generating and plotting line 3x+2y=150
E=np.array([0,75])
F=np.array([50,0])
EF=line_gen(E,F)
plt.plot(EF[0,:],EF[1,:],label='3x+2y=150')

#Shading Required Region
x1=[2,15,40]
y1=[72,20,15]
plt.fill(x1,y1)

#Labelling points
plt.plot(2,72,'o',color='r')
plt.text(2.2,74,'A(2,72)')
plt.plot(15,20,'o',color='r')
plt.text(12,13,'B(15,20)')
plt.plot(40,15,'o',color='r')
plt.text(42,18,'C(40,15)')

plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')