# -*- coding: utf-8 -*-
"""Assignment12_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZKbFC8mv277gmtVOwYBrpIxWEn1XjCxW
"""

#Code by K.A. Raja Babu
#June 19,2021

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[4,1],[1,5],[-3,-2]]).T
b = np.array([80,115,-150]).reshape((3,-1 ))
c = np.array([6,3])

x = Variable((2,1),nonneg = True)

f = c@x
obj = Minimize(f)
# Constraints
constraints = [A.T@x >= b]
Problem(obj, constraints).solve()

print("Minimum_value: " ,(f.value))
print("attained at: ",(x.value))