# -*- coding: utf-8 -*-
"""assignment1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g46uyT0463lcIdt1B6JOzsc55geIampL
"""

import numpy as np

a = np.array([3, -4, 5])
b = np.array([-2, 1, -3])

cross_product = np.cross(a, b)

scalar_product = np.dot(a, b)

print ('Cross product of a and b is '+ str(cross_product))

print ('Scalar product of a and b is ' + str(scalar_product))