# -*- coding: utf-8 -*-
"""assignment12_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x3tRqfLuZPSub1vhUcD3K2y1S7zZICei
"""

# -*- coding: utf-8 -*-
"""Assignment-12_2.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/126XauGg98Mq5QdEZzcww8IabtyhJ3VRW
"""

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[1,1],[-1,2],[1,-3]]).T
b = np.array([1200,0,600]).reshape((3,-1 ))
c = np.array([12,16])

x = Variable((2,1),nonneg = True)

f = c@x
obj = Maximize(f)
# Constraints
constraints = [A.T@x <= b]
Problem(obj, constraints).solve()

print("Maximum_value: " ,(f.value))
print("attained at: ",(x.value))