# -*- coding: utf-8 -*-
"""EE3900_As1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lgqAcTx_qxKOVfbxHiIRGzuiMQjwliim
"""

import numpy as np
import matplotlib.pyplot as plt

#Line points
A = np.array([4,6]) 
B = np.array([1,5]) 
C = np.array([7,2])
#D = np.array([13/4,23/4])
D = (A*(3/4))+(B*(1/4))
#E = np.array([19/4,20/4])
E = (A*(3/4))+(C*(1/4))

#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Generating all lines
x_AB = line_gen(A,B)
x_BC = line_gen(B,C)
x_CA = line_gen(C,A)
x_DE = line_gen(D,E)

#Plotting all lines
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_BC[0,:],x_BC[1,:],label='$BC$')
plt.plot(x_CA[0,:],x_CA[1,:],label='$CA$')
plt.plot(x_DE[0,:],x_DE[1,:],label='$DE$')

plt.plot(A[0], A[1], 'o')
plt.text(A[0] * (1 + 0.04), A[1] * (1 - 0.01) , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(B[0] * (1 - 0.2), B[1] * (1) , 'B')
plt.plot(C[0], C[1], 'o')
plt.text(C[0] * (1 + 0.003), C[1] * (1 + 0.1) , 'C')
plt.plot(D[0],D[1],'o')
plt.text(D[0] * (1 - 0.1), D[1] * (1 + 0.01) , 'D')
plt.plot(E[0],E[1],'o')
plt.text(E[0] * (1 + 0.04), E[1] * (1 - 0.01) , 'E')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()
# area of triangle ABC
ABC = np.vstack((B-A,C-A))
areaABC = 1/2*np.abs(np.linalg.det(ABC))
print("Area of tgle ABC: ", areaABC)
# area of triangle ADE
ADE=np.vstack((D-A,E-A))
areaADE = 1/2*np.abs(np.linalg.det(ADE))
print("Area of tgle ADE: ", areaADE)
print("Ratio: ",areaADE/areaABC)