# -*- coding: utf-8 -*-
"""Assignment 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_g9u5bqh4ap3WXZHmNNqhk5Jby3do1uG
"""

# -*- coding: utf-8 -*-
"""Assignment-9
 
Automatically generated by Colaboratory.
 
Original file is located at
    https://colab.research.google.com/drive/1ezk8dd2gmCWTi6bE7sHTh_uRNuc-w3hY
"""
 
import numpy as np
import matplotlib.pyplot as plt 
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB 
 
#Plotting line 2x+y = 50
A=np.array([25,0])
B=np.array([17.5,15])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='2x+y=50') 
 
#Plotting line x+2y=40
C=np.array([0,20])
D=np.array([25,7.5])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='x+2y=40') 
 
#Shading Required Region
x1=[0,0,20,25]
y1=[0,20,10,0]
plt.fill(x1,y1,color='blue',alpha=0.3)  
 
#Labelling points
plt.plot(0,0,'o',color='r')
plt.text(0,0,'A(0,0)')
plt.plot(25,0,'o',color='r')
plt.text(25,0,'B(25,0)')
plt.plot(0,20,'o',color='r')
plt.text(0,20,'C(0,20)')
plt.plot(20,10,'o',color='r')
plt.text(20,10,'O(20,10)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
 
plt.show()