# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PmQD_ufKZeTwodxZHLet9cTY6xU5V6ZL
"""

import matplotlib.pyplot as plt
import numpy as np
import subprocess
import shlex

x = np.linspace(-20, 20, 100)

y = x**2 - 4*x + 6

plt.plot(x,y,label='y=x^2-4x+6')
plt.grid()


plt.plot(2,2, 'o')
plt.text(2,1,'c')


#show plot
plt.ylim([-1,10])
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend()

plt.show()