# -*- coding: utf-8 -*-
"""Assignment-4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IBR1tKx-xpysDuW28oAfwldmQQfMdI99
"""

import matplotlib.pyplot as plt
import numpy as np
 
x = np.linspace(-2, 2, 100)
 
y = 3*x**2 - 2*x + 1/3
 
a = 3
b = -2
c = 1/3
 
d1 = -b + np.sqrt(b**2-4*a*c)
d2 = -b - np.sqrt(b**2-4*a*c)
d1 = d1/(2*a)
d2 = d2/(2*a)
 
plt.plot(x,y,label='y=3$x^2$-2x+1/3')
plt.grid()
 
plt.plot(d2,0, 'o')
plt.text(d2,0.6, 'A')
plt.plot(d1, 0, 'o')
plt.text(d1,1.7, 'B')
plt.plot(1/3,0, 'o')
plt.text(0.33,0,'c')
 
#show plot
plt.xlabel('$x$');plt.ylabel('$y$')
plt.legend()
 
plt.show()