#! /usr/bin/python3
import numpy as np

a = np.array([[2,0,1],[2,1,3],
            [1,-1,0]])  #Given Matrix  
A = a.dot(a) #Calculate A^2
B=-5*a
C=6*c
sum=A+B+C#Adding matrix to obtain result
print(sum)
