# -*- coding: utf-8 -*-
"""Assignment-7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BvKom8a7I8EOi5N2cRU0dNxtVyY1humb
"""

import numpy as np
import matplotlib.pyplot as plt


O = np.array(([0,0]))

def ellipse_gen(a,b):
	len = 50
	theta = np.linspace(0,2*np.pi,len)
	x_ellipse = np.zeros((2,len))
	x_ellipse[0,:] = a*np.cos(theta)
	x_ellipse[1,:] = b*np.sin(theta)
	x_ellipse = (x_ellipse.T + O).T
	return x_ellipse

#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Standard Ellipse
a = 7.211
b = 3.60
x = ellipse_gen(a,b)

#Vertices
A1 = np.array([a,0])
A2 = -A1
B1 = np.array([0,b])
B2 = -B1
# Plotting points
p = np.array([4,3]) 
q = np.array([6,2])

#Plotting the ellipse
plt.plot(x[0,:],x[1,:],'b' ,label='ellipse')

#Labelling points
plt.plot(0,0, 'o')
plt.text(-0.7 ,-0.3,'O')
plt.plot(4,3, 'o')
plt.text(4.3 ,3.3,'p')
plt.plot(6,2, 'o')
plt.text(6.3 ,2.3,'q')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')

plt.show()