# -*- coding: utf-8 -*-
"""ASSIGNMENT 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bfS-kqpFyACAOnkUoi6oSn_PMwPr9Vhu
"""

import numpy as np
import matplotlib.pyplot as plt
import subprocess
import  shlex
import math
 
#coeffecients
a=6
b=17
c=5
#writing the equation
x = np.linspace(-3,5,100)
p=np.poly1d([a,b,c])
for i in range(len(x)):
    y=p(x)
 
#zeroes
#s=math.sqrt(b**2-4*a*c)
#x_1=(-1*b+s)/(2*a)
#x_2=(-1*b-s)/(2*a)
roots=p.r
 
A=np.array([roots[0],0])
B=np.array([roots[1],0])
plt.plot(A[0], A[1], 'o')
plt.text(A[0] * (1 + 0.1), A[1] * (1 - 0.1) , '$x_1$')
plt.plot(B[0], B[1], 'o')
plt.text(B[0] * (1-0.5), B[1] * (1-0.1) , '$x_2$')
plt.plot(x,y,label='$p(x)=6x^2+17x+5$')
plt.xlabel('$x$')
plt.ylabel('$p(x)$')
plt.legend(loc='best')
plt.grid() # minor
#plt.axis('equal')
plt.show()
