# -*- coding: utf-8 -*-
"""Assignment-9(1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezk8dd2gmCWTi6bE7sHTh_uRNuc-w3hY
"""

from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt
 
A = np.array([[1,3],[3,1]]).T
b = np.array([12,12]).reshape((2,-1 ))
c = np.array([17.5,7])
 
x = Variable((2,1),nonneg = True)
 
f = c@x
obj = Minimize(f)
# Constraints
constraints = [A.T@x >= b]
Problem(obj, constraints).solve()
 
print("Maximum_value: " ,(f.value))
print("attained at: ",(x.value))