# -*- coding: utf-8 -*-
"""Assignment-9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ezk8dd2gmCWTi6bE7sHTh_uRNuc-w3hY
"""



import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Plotting line x+3y = 12
A=np.array([0,4])
B=np.array([12,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='x+3y=12')
 
#Plotting line 3x+y=12
C=np.array([0,12])
D=np.array([4,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='3x+y=12')
 
#Shading Required Region
x1=[0,4,3,3]
y1=[4,0,3,3]
plt.fill(x1,y1,color='blue',alpha=0.3)
 
 
#Labelling points
plt.plot(0,4,'o',color='r')
plt.text(0,4,'A(0,4)')
plt.plot(12,0,'o',color='r')
plt.text(12,0,'B(12,0)')
plt.plot(0,12,'o',color='r')
plt.text(0,12,'C(0,12)')
plt.plot(4,0,'o',color='r')
plt.text(4,0,'D(4,0)')
plt.plot(3,3,'o',color='r')
plt.text(3,3,'O(3,3)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()