# -*- coding: utf-8 -*-
"""Assignment-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jh2iZziO74B8gJuyT-XH3bGHBGrW0x8C
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
len = 100

# Plotting parabola
y = np.linspace(-5,5,100)
x=(y*y + 2)/3
plt.plot(x,y,label='$y^2=4x$')

# Generating points
A = np.array([2.75,8])
B = np.array([-5.25,-8])
P = np.array([4.48,8])
R = np.array([-3.52,-8])
q = np.array([41/48,3/4])

#Generating lines
x_AB = line_gen(A,B)
x_PR = line_gen(P,R) 

#Plotting lines
plt.plot(x_AB[0,:],x_AB[1,:],label='$Parallel line (AB)$')
plt.plot(x_PR[0,:],x_PR[1,:],label='$Tangent (PR)$')



#Plotting points
plt.plot(A[0], A[1], 'o')
plt.text(2.85, 8.3 , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(-5.9, -8.5, 'B')
plt.plot(P[0], P[1], 'o')
plt.text(4.6,8.3, 'P')
plt.plot(R[0], R[1], 'o')
plt.text(-3,-8.2, 'R')
plt.plot(q[0], q[1], 'o')
plt.text(1.3,1, 'q')

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()