# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ql7zboFzox40C_MjTW7hCCqILYLv-wXF
"""

#code by Satya Sangram
#19/05/2021
#Code for Q.NO 2.28

import numpy as np
import matplotlib.pyplot as plt
from coeffs import *

figure, axes = plt.subplots()


A = np.array([0,0]) 
B = np.array([5,0]) 
D = np.array([3.6,4.8]) 


#Generating all lines
x_AB = line_gen(A,B)
x_BD = line_gen(B,D)
x_DA = line_gen(D,A)

#Plotting all lines
plt.plot(x_AB[0,:],x_AB[1,:],label='$AB$')
plt.plot(x_BD[0,:],x_BD[1,:],label='$BD$')
plt.plot(x_DA[0,:],x_DA[1,:],label='$DA$')

plt.plot(A[0], A[1], 'o')
plt.text(0.2, 0.1 , 'A')
plt.plot(B[0], B[1], 'o')
plt.text(B[0] * (1 + 0.02), 0.1 , 'B')
plt.plot(D[0], D[1], 'o')
plt.text(D[0] * (1 + 0.04), D[1] * (1 - 0.1) , 'D')

Drawing_C = plt.Circle(( 0 , 0 ), 4,fill=False)
axes.add_artist( Drawing_C )
plt.plot(4, 0, 'o')
plt.text(4 * (1 + 0.04),0.1 , 'E1') 
plt.plot(0, 4, 'o')
plt.text(0.1 ,4.1, 'E2') 




  

plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid()