# -*- coding: utf-8 -*-
"""Assignment 11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ICYxyoeWSVQfb8tutxe9H9A2IxK9JKHx
"""

# -*- coding: utf-8 -*-
"""Assignment-11(a).ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1uWix_ThZqrBlRZNrbg7berH8ZKPHw_0A
"""
 
import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Generating and plotting line 2x+y = 80
A=np.array([0,80])
B=np.array([40,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='2x+y= 80')
 
#Generating and plotting line 2x+3y = 120
C=np.array([0,40])
D=np.array([60,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='2x+3y=120')
 
 
#Shading Required Region
x1=[0, 40,30,0]
y1=[0,0,20,40]
plt.fill(x1,y1,color='green',alpha=0.3)
 
#Labelling points
plt.plot(0, 40,'o',color='r')
plt.text(0, 40,'A(0, 40)')
plt.plot(30,20,'o',color='r')
plt.text(30,20,'B(30,20)')
plt.plot(40,0,'o',color='r')
plt.text(40,0,'C(40,0)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')