# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iq1Z4Jh_1opLdOeQZ24HQM7AgqSYGTUP
"""

# -*- coding: utf-8 -*-
"""Assignment-11(b).ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/126XauGg98Mq5QdEZzcww8IabtyhJ3VRW
"""
 
from cvxpy import *
import numpy as np
import matplotlib.pyplot as plt
 
A = np.array([[2,1],[2,3]]).T
b = np.array([80,120]).reshape((2,-1 ))
c = np.array([7,10])
 
x = Variable((2,1),nonneg = True)
 
f = c@x
obj = Maximize(f)
# Constraints
constraints = [A.T@x <= b]
Problem(obj, constraints).solve()
 
print("Maximum_value: " ,(f.value))
print("attained at: ",(x.value))