# -*- coding: utf-8 -*-
"""Assignment11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4uGtnhOtv4P44277zg-xnL6sPEPhIgA
"""

#Code by K.A. Raja Babu
#June 21, 2021

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Generating and plotting line 4x+3y = 60
A=np.array([0,20])
B=np.array([15,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='4x+3y=60')

#Generating and plotting line x=3
C=np.array([3,25])
D=np.array([3,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='x=3')

#Generating and plotting line y=2x
E=np.array([0,0])
F=np.array([10,20])
EF=line_gen(E,F)
plt.plot(EF[0,:],EF[1,:],label='y=2x')

#Shading Required Region
x1=[6,3,3]
y1=[12,16,6]
plt.fill(x1,y1)

#Labelling points
plt.plot(6,12,'o',color='r')
plt.text(7.2,12.5,'A(6,12)')
plt.plot(3,16,'o',color='r')
plt.text(3.5,17,'B(3,16)')
plt.plot(3,6,'o',color='r')
plt.text(4,6,'C(3,6)')

plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')