# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ER5TC9ISyC2j5AuAKGXfGLXbdlYG2ZhU
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Generating and plotting line 3x+4y=60
A=np.array([20,0])
B=np.array([0,15])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='3x+4y=60')

#Generating and plotting line x+3y=30
C=np.array([0,10])
D=np.array([30,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='x+3y=30')



#Shading Required Region
x1=[C[0],0,A[0],12]
y1=[C[1],0,A[1],6]
plt.fill(x1,y1,color='k',label='feasible region')

#Labelling points
plt.plot(C[0],C[1],'o',color='r')
plt.text(0,11,"A(0,10)")

plt.plot(12,6,'o',color='r')
plt.text(13,6.5,"B(12,6)")

plt.plot(A[0],A[1],'o',color='r')
plt.text(21,0,"C(20,0)")

plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()