# -*- coding: utf-8 -*-
"""assignment10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xr-2O27DlzuQP8sQGlPsrjE3UD470xhe
"""

# -*- coding: utf-8 -*-
"""Assignment10_1.ipynb
Automatically generated by Colaboratory.
Original file is located at
   https://colab.research.google.com/drive/1Xr-2O27DlzuQP8sQGlPsrjE3UD470xhe 
"""

#Gross profit of market-1 & market-2
#Code by Ramya Tulasi
#June,23 2021
import numpy as np
import matplotlib.pyplot as plt
  
N = 2
ind = np.arange(N) 
width = 0.25
  
xvals = [46000,53000]
bar1 = plt.bar(ind, xvals, width, color = 'r')
  
yvals = [31000,36000]
bar2 = plt.bar(ind+width, yvals, width, color='g')
  
zvals = [15000,17000]
bar3 = plt.bar(ind+width*2, zvals, width, color = 'b')
  
plt.title("Market-I & II")
  
plt.xticks(ind+width,['Market-I', 'Market-II'])
plt.legend( (bar1, bar2, bar3), ('Revenue', 'Unit cost', 'Profit') )
plt.show()