# -*- coding: utf-8 -*-
"""assignment11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5a0Otpx0kpinm2wHNIwTJoQLDNl6yaj
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Generating and plotting line x+3y=30
C=np.array([0,10])
D=np.array([6.6666,0])
CD=line_gen(C,D)
plt.plot(CD[0,:],CD[1,:],label='3x+2y=20')

#Generating and plotting line 3x+4y=60
A=np.array([6,0])
B=np.array([2,8])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='2x+y=12')


#Shading Required Region
x1=[C[0],0,A[0],4]
y1=[C[1],0,A[1],4]
plt.fill(x1,y1,color='g',alpha=0.3,label='feasible region')

#Labelling points
plt.plot(C[0],C[1],'o',color='r')
plt.text(0.5,10,"A(0,10)")

plt.plot(4,4,'o',color='r')
plt.text(4.5,4.5,"B(4,4)")

plt.plot(A[0],A[1],'o',color='r')
plt.text(6.2,0,"C(6,0)")

plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')

#if using termux
plt.savefig('assignment11.png')
#else
plt.show()