# -*- coding: utf-8 -*-
"""assignment10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwYGehC52fUIb56aS8sSFKJZdgy88j65
"""

import numpy as np
import matplotlib.pyplot as plt

#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#Plotting line 2x+y = 8
A=np.array([6,-4])
B=np.array([-1,10])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='2x+y=8')

#Plotting line x+2y=10
P=np.array([-2,6])
Q=np.array([18,-4])
PQ=line_gen(P,Q)
plt.plot(PQ[0,:],PQ[1,:],label='x+2y=10')

#Shading Required Region
x1=[-1,2,18,20]
y1=[10,4,-4,10]
plt.fill(x1,y1,color='green',alpha=0.3)

#Labelling points
plt.plot(-1,10,'o',color='r')
plt.text(-1.2,10.5,'A(-1,10)')
plt.plot(2,4,'o',color='r')
plt.text(2.2,4.2,'B(2,4)')
plt.plot(18,-4,'o',color='r')
plt.text(18.2,-4.2,'C(18,-4)')

#if using termux
plt.savefig('assignment10.png')
#else


plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')

#if using termux
plt.savefig('assignment10.png')
#else

plt.show()