# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EiNdik7ZCB-L0qJtxtHHOQ0Yk7eWbreu
"""

#Code by Satya Sangram
#For Matrices 2.64
import numpy as np
import matplotlib.pyplot as plt

N = 2
ind = np.arange(N) 
width = 0.25

#Input Parameters
B=np.array([[1000 , 500 , 5000], [3000, 1000, 10000]])
B=B.reshape(2,3)
A=np.array([40,100,50])
A=A.reshape(3,1)

X=np.matmul(B,A)
X=X.reshape(1,2)
  
xvals = [X[0][0]/100,X[0][1]/100]
bar1 = plt.bar(ind, xvals, width, color = 'r',label='total')
  
plt.xlabel("Cities")
plt.ylabel('Cost(in Rupees)')
plt.title("Total Amount Spent(in Rupees)")
  
plt.xticks(ind,['X', 'Y'])
plt.legend()
plt.show()